"""Utilities for employee-domain workflows."""

from hrm_backend.employee.utils.conversions import HIRE_CONVERSION_STATUS_READY
from hrm_backend.employee.utils.onboarding import (
    ONBOARDING_RUN_STATUS_STARTED,
    ONBOARDING_TASK_STATUS_COMPLETED,
    ONBOARDING_TASK_STATUS_IN_PROGRESS,
    ONBOARDING_TASK_STATUS_PENDING,
)

__all__ = [
    "HIRE_CONVERSION_STATUS_READY",
    "ONBOARDING_RUN_STATUS_STARTED",
    "ONBOARDING_TASK_STATUS_PENDING",
    "ONBOARDING_TASK_STATUS_IN_PROGRESS",
    "ONBOARDING_TASK_STATUS_COMPLETED",
]
