"""Internal schemas for employee-domain workflows."""

from hrm_backend.employee.schemas.avatar import (
    EmployeeAvatarDeleteResponse,
    EmployeeAvatarDownloadPayload,
    EmployeeAvatarUploadResponse,
)
from hrm_backend.employee.schemas.conversion import (
    HireConversionCandidateSnapshot,
    HireConversionCreate,
    HireConversionOfferSnapshot,
    HireConversionStatus,
)
from hrm_backend.employee.schemas.onboarding import (
    EmployeeOnboardingPortalResponse,
    EmployeeOnboardingTaskResponse,
    EmployeeOnboardingTaskUpdateRequest,
    OnboardingDashboardDetailResponse,
    OnboardingDashboardListItemResponse,
    OnboardingDashboardListResponse,
    OnboardingDashboardSummaryResponse,
    OnboardingDashboardTaskResponse,
    OnboardingRunCreate,
    OnboardingRunStatus,
    OnboardingTaskCreate,
    OnboardingTaskListResponse,
    OnboardingTaskResponse,
    OnboardingTaskStatus,
    OnboardingTaskUpdateRequest,
)
from hrm_backend.employee.schemas.profile import (
    EmployeeDirectoryAvatarResponse,
    EmployeeDirectoryListItemResponse,
    EmployeeDirectoryListResponse,
    EmployeeDirectoryProfileResponse,
    EmployeeProfileCreate,
    EmployeeProfileCreateRequest,
    EmployeeProfilePrivacySettingsResponse,
    EmployeeProfilePrivacyUpdateRequest,
    EmployeeProfileResponse,
)
from hrm_backend.employee.schemas.template import (
    OnboardingChecklistTemplateCreateRequest,
    OnboardingChecklistTemplateItemResponse,
    OnboardingChecklistTemplateItemUpsert,
    OnboardingChecklistTemplateItemWrite,
    OnboardingChecklistTemplateListResponse,
    OnboardingChecklistTemplateResponse,
    OnboardingChecklistTemplateUpdateRequest,
    OnboardingChecklistTemplateUpsert,
)

__all__ = [
    "HireConversionStatus",
    "HireConversionCandidateSnapshot",
    "HireConversionOfferSnapshot",
    "HireConversionCreate",
    "EmployeeOnboardingPortalResponse",
    "EmployeeOnboardingTaskResponse",
    "EmployeeOnboardingTaskUpdateRequest",
    "OnboardingDashboardSummaryResponse",
    "OnboardingDashboardListItemResponse",
    "OnboardingDashboardListResponse",
    "OnboardingDashboardTaskResponse",
    "OnboardingDashboardDetailResponse",
    "OnboardingRunStatus",
    "OnboardingRunCreate",
    "OnboardingTaskStatus",
    "OnboardingTaskCreate",
    "OnboardingTaskUpdateRequest",
    "OnboardingTaskResponse",
    "OnboardingTaskListResponse",
    "EmployeeProfileCreateRequest",
    "EmployeeProfileCreate",
    "EmployeeDirectoryAvatarResponse",
    "EmployeeDirectoryListItemResponse",
    "EmployeeDirectoryListResponse",
    "EmployeeDirectoryProfileResponse",
    "EmployeeProfileResponse",
    "EmployeeProfilePrivacySettingsResponse",
    "EmployeeProfilePrivacyUpdateRequest",
    "EmployeeAvatarUploadResponse",
    "EmployeeAvatarDeleteResponse",
    "EmployeeAvatarDownloadPayload",
    "OnboardingChecklistTemplateItemWrite",
    "OnboardingChecklistTemplateCreateRequest",
    "OnboardingChecklistTemplateUpdateRequest",
    "OnboardingChecklistTemplateItemUpsert",
    "OnboardingChecklistTemplateUpsert",
    "OnboardingChecklistTemplateItemResponse",
    "OnboardingChecklistTemplateResponse",
    "OnboardingChecklistTemplateListResponse",
]
